### ISSUE TITLE
Is not an issue

### ISSUE THREAD

**Issue by jabawack81** [noorus/php-psn#2]
I know this is not an issue but I didn't find any other way to contact you.

I'd like to use your library in my site but I cant retrieve the user data were I can contact you?

Thanks

Jaba

**Comment by noorus** [comment]
Perhaps the API has changed. I don't really actively work on this project at the moment. You can try looking for the current method in the web; current information is usually available on certain PS modding/hacking forums.

**Comment by jabawack81** [comment]
Thanks.

Jaba
